quality: [50, 95]

background:
  image:
    paths: [resources/background]
    weights: [1]

  effect:
    args:
      # gaussian blur
      - prob: 1
        args:
          sigma: [0, 10]

document:
  fullscreen: 0.5
  landscape: 0.5
  short_size: [720, 1024]
  aspect_ratio: [1, 2]
  margin: [0, 0.2]
  content:
    table:
      static:
        weight: 1
        html_paths: [ resources/table_html ]
        image_paths: [ resources/table_image ]
        path_weights: [1]
        lower_image_size_ratios: [0.9]
      synth:
        weight: 5
        html:
          paths: [ resources/table_html ]
          weights: [1]
          synth_structure_prob: 0.0
          synth_content_prob: 0.0
          synth_structure: []
          synth_content: []
        style:
          #table 템플릿 몇개 정하기
          row_striped:
            weight: 1
            background_color: []
#          dark:
#            weight: 1
#            theads: [ ]
#            line_template: [ ]
#          random:
#            weight: 4
#            table: []
#            thead: []
#            tbody: []
#            tr: []
#            td: []
#            local:
#              prob: 0.4
#              tr: []
#              td: []
          common:
            background:
              paper:
                image:
                  paths: [ resources/paper ]
                  weights: [ 1 ]
                  alpha: [ 0, 0.2 ]
                  grayscale: 0.5
                  crop: 1
              color: []
              gradient: []
            border: []
            text: []
            bg: []
            padding: []
            size: []
            margin: []
            round: []
      common:
        image_border:
          color: [ 1,3 ]
          top: [ 1,3 ]
          bottom: [ 1,3 ]
          left: [ 1,3 ]
          right: [ 1,3 ]
          width: [ 1,3 ]
          same_width: 0.5
        image_margin:
          color: [ 1,3 ]
          top: [ 1,3 ]
          bottom: [ 1,3 ]
          left: [ 1,3 ]
          right: [ 1,3 ]
          width: [ 1,1 ]
          same_width: 1
        rows: [2, 10]
        cols: [2, 10]
        has_span: 0.5
        has_col_span: 0.5
        has_row_span: 0.5
        tmp_path: tmp



#      weights: [10,90]
#      args:
#        # HtmlAndImageFile iterator
#        - args:
#          # HtmlAndImageFile
#          - html_paths: [ resources/table_html ]
#            image_paths: [ resources/table_image ]
#            weights: [ 1 ]
#          # Image Border Switch
#          - prob: 0.5
#            args:
#              width: []
#              color: []
#          # Image Margin Switch
#          - prob: 0.5
#            args:
#              # margin selector
#              weights: [5,5]
#              args:
#                # 위,아래,왼,우 동일하게 적용
#                - length: [ ]
#                # 위,아래,왼,우 각각 적용
#                - left: [ ]
#                  top: [ ]
#                  right: [ ]
#                  bottom: [ ]
#        # Synth htmls and images iterator:
#        - args:
#          # table html selector
#          - weights: []
#            args:
#              # html file and synth contents iterator
#              - args:
#                # html file
#                - paths: []
#                  weights: [1]
#                # synth table content switch
#                - prob: 0.5
#                  args:
#                    # synth table content selector
#                    - weights: []
#                      args:
#                        # corpus
#                        - paths: []
#                          weights: []
#                        # synth text
#                        - paths: [ ]
#                          weights: [ ]
#                        # key value corpus
#                        - paths: [ ]
#                          weights: [ ]
#              # synth table structure and contents iterator
#              - args:
#                # synth table structure html
#                - rows: [ ]
#                  cols: [ ]
#                # synth table content selector
#                - weights: [ ]
#                  args:
#                    # corpus
#                    - paths: [ ]
#                      weights: [ ]
#                    # synth text
#                    - paths: [ ]
#                      weights: [ ]
#                    # key value corpus
#                    - paths: [ ]
#                      weights: [ ]
#          # table styles iterator
#          - args:
#            # table global styles template selector
#            - weights: []
#              args:
#                # table global random synth styles iterator
#                - args:
#                  # table tag global style iterator
#                  - args:
#                    # bg selector
#                    - weights: [ 1,1,1,1 ]
#                      args:
#                        # color
#                        # gradient
#                        # image
#                        # paper
#                        - paths: [ resources/paper ]
#                          weights: [ 1 ]
#                          alpha: [ 0, 0.2 ]
#                          grayscale: 1
#                          crop: 1
#                  # thead tag global style iterator
#                  # tbody tag global style iterator
#                  # tr tag global style iterator
#                  # td tag global style iterator
#                # striped rows
#                - args:
#                # simple table styles
#            # tr individually style switch
#            - prob: 0.3
#              args:
#            # td individually style switch
#            - prob: 0.3
#              args:


#        - html:
#            paths: [ resources/html ]
#            weights: [ 1 ]
#            table:
#              cols: [ 2,20 ]
#              rows: [ 2,20 ]
#              header:
#                prob: 0.5
#                args:
#                  rows: [ 1, 2 ]
#              style:
#              background:
#                weights: [ 1,1,1,1 ]
#                color:
#                gradient:
#                image:
#                paper:
#                  image:
#                    paths: [ resources/paper ]
#                    weights: [ 1 ]
#                    alpha: [ 0, 0.2 ]
#                    grayscale: 1
#                    crop: 1
#              thead:
#                background:
#                  weights: [ 1,1,1,1 ]
#                  color:
#                  gradient:
#                tr:
#                  td:
#              tbody:
#                tr:
#                  td:


    text:
      path: resources/corpus/kowiki.txt
    font:
      paths: [resources/font/ko]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.0334, 0.1]
      max_row: 10
      max_col: 3
      fill: [0.5, 1]
      full: 0.1
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.5, 1]
      stack_full: 0.1
    textbox:
      fill: [0.5, 1]
    textbox_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1
    content_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1

  effect:
    args:
      # elastic distortion
      - prob: 1
        args:
          alpha: [0, 1]
          sigma: [0, 0.5]
      # gaussian noise
      - prob: 1
        args:
          scale: [0, 8]
          per_channel: 0
      # perspective
      - prob: 1
        args:
          weights: [750, 50, 50, 25, 25, 25, 25, 50]
          args:
            - percents: [[0.75, 1], [0.75, 1], [0.75, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [0.75, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [1, 1]]

effect:
  args:
    # color
    - prob: 0.2
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 1
      args:
        intensity: [0, 160]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # contrast
    - prob: 1
      args:
        alpha: [1, 1.5]
    # brightness
    - prob: 1
      args:
        beta: [-48, 0]
    # motion blur
    - prob: 0.5
      args:
        k: [3, 5]
        angle: [0, 360]
    # gaussian blur
    - prob: 0.5
      args:
        sigma: [0, 1.5]
