quality: [50, 95]

background:
  image:
    paths: [resources/background]
    weights: [1]

  effect:
    args:
      # gaussian blur
      - prob: 0.7
        args:
          sigma: [0, 10]

document:
  fullscreen: 0.5
  landscape: 0.5
  short_size: [720, 1024]
  aspect_ratio: [1, 2]
  margin: [0, 0.2]
  content:
    table:
      static:
        weight: 1
        image:
          paths: [ resources/table_image ]
          lower_image_size_ratios: [ 0.9 ]
        html:
          paths: [ resources/table_html ]
          weights: [ 1 ]
          min_row: 2
          max_row: 10
          min_col: 2
          max_col: 10
          has_span:
            prob: 0.5
          has_col_span:
            prob: 0.5
          has_row_span:
            prob: 0.5
          tmp_path: tmp
      synth:
        weight: 4
        html:
          paths: [ resources/table_html ]
          weights: [1]
          synth_structure:
            prob: 0.0
          synth_content:
            prob: 0.0
          min_row: 2
          max_row: 10
          min_col: 2
          max_col: 10
          has_span:
            prob: 0.5
          has_col_span:
            prob: 0.5
          has_row_span:
            prob: 0.5
          tmp_path: tmp
        style:
          font:
            paths: [ ]
            weights: []
          color_set:
            dark: [black, red, blue, green, orange, purple, navy, gray, BlueViolet, Brown, CadetBlue, Chocolate, CornflowerBlue, Crimson, DarkBlue, DarkCyan, DarkGoldenRod, DarkGreen, darkmagenta, darkolivegreen, darkorchid, darkred, darkslateblue, darkslategray, darkturquoise, darkviolet, deeppink, deepskyblue, dimgray, dodgerblue, firebrick, forestgreen, fuchsia, indianred, indigo, lightseagreen, lightslategray, limegreen, magenta, maroon, mediumblue, mediumorchid, tomato, violet]
            light: [white, AliceBlue, AntiqueWhite, Aqua, Aquamarine, Azure, Beige, Bisque, BlancedAlmond, BurlyWood, Chartreuse, Coral, Cornsilk, Cyan, DarkGray, DarkGrey, darkkhaki, darkorange,darksalmon, darkseagreen, floralwhite, gainsboro, ghostwhite, gold, goldenrod, greenyellow, honeydew, hotpink, ivory, khaki,lavender, lavenderblush, lawngreen, lemonchiffon, lightblue, lightcoral, lightcyan, lightgoldenrodyellow, lightgray, lightgreen, lightpink, lightsalmon, lightskyblue, lightsteelblue, lightyellow, lime, linen, mediumaquamarine]
          global:
            absolute:
              thead:
                color_mode: [dark, light]
                border_type: [empty, all, bottom, top_bottom]
                border_width: [1, 5]
              table_outline:
                border_type: [ empty, all, top_bottom ]
                border_width: [ 1, 5 ]
              background:
                paper:
                  weight: 1
                  paths: [ resources/paper ]
                  weights: [ 1 ]
                  alpha: [ 0, 0.2 ]
                  grayscale: 0.5
                  crop: 1
                gradient:
                  weight: 1
                  type: [linear, radial, conic, repeating-linear]
                  angle: [0, 359] # angle은 linear와,repeating만
                  num_colors: [2, 5]
                  use_random_stop_position:
                    prob: 0.3
                solid:
                  weight: 1
                striped:
                  weight: 1
                  dark_line: [odd, even]
                striped_all_colors:
                  weight: 1
                multi_color:
                  weight: 1
              border:
                empty:
                  weight: 1
                  td:
                    border: 0px
                inside:
                  weight: 1
                  table:
                    border-style: hidden
                  td:
                    border-width:
                      values: [1, 3]
                      postfix: "px"
                    border-style: solid
                all:
                  weight: 1
                  td:
                    border-width:
                      values: [ 1, 3 ]
                      postfix: "px"
                    border-style: solid
                row:
                  weight: 1
                  tr:
                    border-bottom-width:
                      values: [1, 3]
                      postfix: "px"
                    border-bottom-style: solid
                col:
                  weight: 1
                  td:
                    border-right-width:
                      values: [ 1, 3 ]
                      postfix: "px"
                    border-right-style: solid
                  table:
                    border-style: hidden
                outline:
                  weight: 1
                  table:
                    border-width:
                      values: [1, 3]
                      postfix: "px"
                    border-style: solid
              table:
                color_mode: [ dark, light ]
            relative:
              table:
                width_scale: [ 1.0, 1.3 ]
                height_scale: [ 1.0, 1.3 ]
            css:
              table:
  #              color: [] # font color
  #              font: []
                border-radius:
                  prob: 0.3
                  values: [ 1, 10 ]
                  postfix: "px"
                margin:
                  prob: 0.5
                  values: [ 1, 50 ]
                  postfix: "px"
                margin-left:
                  prob: 0.5
                  values: [ 1, 50 ]
                  postfix: "px"
                margin-right:
                  prob: 0.5
                  values: [ 1, 50 ]
                  postfix: "px"
                margin-top:
                  prob: 0.5
                  values: [ 1, 50 ]
                  postfix: "px"
                margin-bottom:
                  prob: 0.5
                  values: [ 1, 50 ]
                  postfix: "px"
                font-size:
                  values: [8, 30]
                  postfix: "px"
  #              text-align: [left, right, center]
                text-align: [left, center]
                vertical-align:
                  values: [top, middle, bottom]
                  weights: [1,10,1]
  #              font-weight: [lighter, bold, normal]
                font-weight: [lighter, normal]
                font-style:
                  values: [normal, italic]
                  weights: [9, 1]
#                text-decoration:
#  #                values: [ none, underline, line-through ]
#                  values: [ none, underline ]
#                  weights: [ 10, 1 ]
                letter-spacing:
                  values: [0, 5]
                  postfix: "px"
                word-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                #text-shadow
                #text-shadow: 4px 4px 5px red;
                #text-shadow: 1px 1px 1px red, 2px 2px 1px red;
              td:
                padding: [2, 20]

#              width: []
#              height: [ ]
            #table 템플릿 몇개 정하기
            # bg 템플릿
            # 라인 템플릿
            # bg & fg 컬러 템플릿
          local:
            prob: 0.5
            absolute:
              tr:
                color_mode: [light, dark]
              td:
                color_mode: [light, dark]
            relative:
              tr:
                prob: 0.1
                font_size: [0.8, 1.2]
              td:
                prob: 0.1
                font_size: [0.8, 1.2]
            css:
              thead:
                prob: 0.5
                font-weight: [ bold, normal ]
                text-align:
                  values: [ left, center ]
                  prob: 0.5
              tbody:
                prob: 0.5
                text-align:
                  values: [ left, center ]
                  prob: 0.5
              tr:
                prob: 0.5
                #              color: [] # font color
                #              font: []
#                text-align:
#                  values: [ left, center ]
#                  prob: 0.1
#                vertical-align: [top, middle, bottom]
                #              font-weight: [lighter, bold, normal]
                font-weight: [ lighter, normal ]
                font-style: [ normal, italic ]
                text-decoration:
                  #                values: [ none, underline, line-through ]
                  values: [ none, underline ]
                  weights: [ 10, 5 ]
                letter-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                word-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                border-width:
                  values: [ 0, 4 ]
                  postfix: "px"
                border-style: [none, solid]
                border-top-width:
                  values: [ 0, 4 ]
                  postfix: "px"
                border-top-style: [none, solid]
                border-left-width:
                  values: [ 0, 4 ]
                  postfix: "px"
                border-left-style: [none, solid]
                border-right-width:
                  values: [ 0, 4 ]
                  postfix: "px"
                border-right-style: [none, solid]
                border-bottom-width:
                  values: [ 0, 4 ]
                  postfix: "px"
                border-bottom-style: [none, solid]
                #text-shadow
                #text-shadow: 4px 4px 5px red;
                #text-shadow: 1px 1px 1px red, 2px 2px 1px red;
              td:
                prob: 0.5
                #              color: [] # font color
                #              font: []
#                text-align: [ left, center ]
#                vertical-align: [top, middle, bottom]
                font-weight: [lighter, bold, normal]
                font-style: [ normal, italic ]
                text-decoration:
                  values: [ none, underline, line-through ]
                  weights: [ 10, 1, 1 ]
                letter-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                word-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                border-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-style: [solid]
                border-top-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-top-style: [ solid ]
                border-left-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-left-style: [ solid ]
                border-right-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-right-style: [ solid ]
                border-bottom-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-bottom-style: [ solid ]
                #text-shadow
                #text-shadow: 4px 4px 5px red;
                #text-shadow: 1px 1px 1px red, 2px 2px 1px red;
                #              width: []
                #              height: [ ]
    text:
      path: resources/corpus/kowiki.txt
    font:
      paths: [resources/font/ko]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.0334, 0.1]
      max_row: 10
      max_col: 3
      fill: [0.5, 1]
      full: 0.1
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.5, 1]
      stack_full: 0.1
    textbox:
      fill: [0.5, 1]
    textbox_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1
    content_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1

  effect:
    args:
      # elastic distortion
      - prob: 1
        args:
          alpha: [0, 1]
          sigma: [0, 0.5]
      # gaussian noise
      - prob: 1
        args:
          scale: [0, 8]
          per_channel: 0
      # perspective
      - prob: 1
        args:
          weights: [750, 50, 50, 25, 25, 25, 25, 50]
          args:
            - percents: [[0.75, 1], [0.75, 1], [0.75, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [0.75, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [1, 1]]

effect:
  args:
    # color
    - prob: 0.2
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 1
      args:
        intensity: [0, 160]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # contrast
    - prob: 1
      args:
        alpha: [1, 1.5]
    # brightness
    - prob: 1
      args:
        beta: [-48, 0]
    # motion blur
    - prob: 0.5
      args:
        k: [3, 5]
        angle: [0, 360]
    # gaussian blur
    - prob: 0.5
      args:
        sigma: [0, 1.5]
