quality: [50, 95]

background:
  image:
    paths: [resources/background]
    weights: [1]

  effect:
    args:
      # gaussian blur
      - prob: 0.7
        args:
          sigma: [0, 10]

document:
  fullscreen: 0.5
  landscape: 0.5
  short_size: [720, 1024]
  aspect_ratio: [1, 2]
  margin: [0, 0.2]
  content:
    table:
      static:
        weight: 1
        html_paths: [ resources/table_html ]
        image_paths: [ resources/table_image ]
        path_weights: [1]
        lower_image_size_ratios: [0.9]
      synth:
        weight: 5
        html:
          paths: [ resources/table_html ]
          weights: [1]
          synth_structure_prob: 0.0
          synth_content_prob: 0.0
          synth_structure: []
          synth_content: []
        style:
          color_set:
            dark: [black, red, blue, green, orange, purple, navy, gray]
            light: [white]
          global:
            ### 밝은색, 어두운색 각각 세트 지정하고, (모든 경우의 수를 조합해도 글씨가 잘보이도록 각각 컬러 선정해야함.)
            ### 다크 모드일경우와 라이트 모드일 경우에 맞게 글자가 잘 보이도록 각 컬러를 랜덤으로 선정.
            ## color attrs
            # border-color
            # color
            # background-color
            ## color targets
            # table
            # thead
            # tbody
            ## dark color세트 세팅(배경, )
            ## second dark 어두운색 세트 세팅
            ## light color 밝은색 세트 세팅
            ## 컬러 반전 여부
            absolute:
              thead:
                prob: 0.5
                color_mode: [dark, light]
              background:
                paper:
                  weight: 1
                  paths: [ resources/paper ]
                  weights: [ 1 ]
                  alpha: [ 0, 0.2 ]
                  grayscale: 0.5
                  crop: 1
                solid:
                  weight: 0
                gradient:
                  weight: 0
                  type: [linear, radial, conic, repeating]
                  angle: [0, 359] # angle은 linear와,repeating만
                  num_colors: [2, 5]
                  use_random_stops:
                    prob: 0.3
                striped:
                  weight: 0
                striped_all_highlight:
                  weight: 0
              border:
                empty: []
                paper_style: []
                row: []
                col: []
                all: []
  #              border-radius: 6px
              table:
                color_mode: [ dark, light ]
            relative:
              table:
                width_scale: [ 1.0, 1.3 ]
                height_scale: [ 1.0, 1.3 ]
            css:
              table:
  #              color: [] # font color
  #              font: []
                margin:
                  prob: 0.5
                  values: [ 1, 50 ]
                margin-left:
                  prob: 0.5
                  values: [ 1, 50 ]
                margin-right:
                  prob: 0.5
                  values: [ 1, 50 ]
                margin-top:
                  prob: 0.5
                  values: [ 1, 50 ]
                margin-bottom:
                  prob: 0.5
                  values: [ 1, 50 ]
                font-size:
                  values: [8, 30]
                  postfix: "px"
  #              text-align: [left, right, center]
                text-align: [left, center]
                vertical-align:
                  values: [top, middle, bottom]
                  weights: [1,10,1]
  #              font-weight: [lighter, bold, normal]
                font-weight: [lighter, normal]
                font-style:
                  values: [normal, italic]
                  weights: [9, 1]
#                text-decoration:
#  #                values: [ none, underline, line-through ]
#                  values: [ none, underline ]
#                  weights: [ 10, 1 ]
                letter-spacing:
                  values: [0, 5]
                  postfix: "px"
                word-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                #text-shadow
                #text-shadow: 4px 4px 5px red;
                #text-shadow: 1px 1px 1px red, 2px 2px 1px red;
              td:
                padding: [2, 20]

#              width: []
#              height: [ ]
            #table 템플릿 몇개 정하기
            # bg 템플릿
            # 라인 템플릿
            # bg & fg 컬러 템플릿
          local:
            prob: 0.5
            absolute:
              tr:
                color_mode: [light, dark]
              td:
                color_mode: [light, dark]
            relative:
              tr:
                prob: 0.1
                font_size: [0.8, 1.2]
              td:
                prob: 0.1
                font_size: [0.8, 1.2]
            css:
              thead:
                prob: 0.5
                font-weight: [ bold, normal ]
                text-align:
                  values: [ left, center ]
                  prob: 0.5
              tbody:
                prob: 0.5
                text-align:
                  values: [ left, center ]
                  prob: 0.5
              tr:
                prob: 0.5
                #              color: [] # font color
                #              font: []
#                text-align:
#                  values: [ left, center ]
#                  prob: 0.1
#                vertical-align: [top, middle, bottom]
                #              font-weight: [lighter, bold, normal]
                font-weight: [ lighter, normal ]
                font-style: [ normal, italic ]
                text-decoration:
                  #                values: [ none, underline, line-through ]
                  values: [ none, underline ]
                  weights: [ 10, 5 ]
                letter-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                word-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                border-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-style: [ solid ]
                border-top-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-top-style: [ solid ]
                border-left-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-left-style: [ solid ]
                border-right-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-right-style: [ solid ]
                border-bottom-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-bottom-style: [ solid ]
                #text-shadow
                #text-shadow: 4px 4px 5px red;
                #text-shadow: 1px 1px 1px red, 2px 2px 1px red;
              td:
                prob: 0.5
                #              color: [] # font color
                #              font: []
#                text-align: [ left, center ]
#                vertical-align: [top, middle, bottom]
                font-weight: [lighter, bold, normal]
                font-style: [ normal, italic ]
                text-decoration:
                  values: [ none, underline, line-through ]
                  weights: [ 10, 1, 1 ]
                letter-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                word-spacing:
                  values: [ 0, 5 ]
                  postfix: "px"
                border-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-style: [solid]
                border-top-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-top-style: [ solid ]
                border-left-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-left-style: [ solid ]
                border-right-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-right-style: [ solid ]
                border-bottom-width:
                  prob: 0.2
                  values: [ 0, 4 ]
                  postfix: "px"
                border-bottom-style: [ solid ]
                #text-shadow
                #text-shadow: 4px 4px 5px red;
                #text-shadow: 1px 1px 1px red, 2px 2px 1px red;
                #              width: []
                #              height: [ ]
      common:
        rows: [2, 10]
        cols: [2, 10]
        has_span: 0.5
        has_col_span: 0.5
        has_row_span: 0.5
        tmp_path: tmp
    text:
      path: resources/corpus/kowiki.txt
    font:
      paths: [resources/font/ko]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.0334, 0.1]
      max_row: 10
      max_col: 3
      fill: [0.5, 1]
      full: 0.1
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.5, 1]
      stack_full: 0.1
    textbox:
      fill: [0.5, 1]
    textbox_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1
    content_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1

  effect:
    args:
      # elastic distortion
      - prob: 1
        args:
          alpha: [0, 1]
          sigma: [0, 0.5]
      # gaussian noise
      - prob: 1
        args:
          scale: [0, 8]
          per_channel: 0
      # perspective
      - prob: 1
        args:
          weights: [750, 50, 50, 25, 25, 25, 25, 50]
          args:
            - percents: [[0.75, 1], [0.75, 1], [0.75, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [0.75, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [1, 1]]

effect:
  args:
    # color
    - prob: 0.2
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 1
      args:
        intensity: [0, 160]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # contrast
    - prob: 1
      args:
        alpha: [1, 1.5]
    # brightness
    - prob: 1
      args:
        beta: [-48, 0]
    # motion blur
    - prob: 0.5
      args:
        k: [3, 5]
        angle: [0, 360]
    # gaussian blur
    - prob: 0.5
      args:
        sigma: [0, 1.5]
